# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ae99626b592f916f9d04db1036a40ad80efcdfa7facf35951285c0e303e3187b43518b9eeeca87a577e32597b1e166015a0eeafc3b77559092182653e56acba

test:
  secret_key_base: bc83937c215620ac00f8cb19179ded0bde1ae23cba98b15bd5ee59ab0c081672c7023ca452cceedf191a28f47893880e7a85bd44b473458838fead23c6e97b9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
